import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // These "React Compiler readiness" rules are noise here — the compiler
      // is intentionally disabled (--no-react-compiler) and useSession's
      // module-level `cache` object is a deliberate external store (mirrors
      // the original Expo app), not local component state.
      "react-hooks/immutability": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @serwist/next at build time — not source.
    "public/sw.js",
    "public/sw.js.map",
    "public/swe-worker-*.js",
    "public/swe-worker-*.js.map",
    // One-off maintenance scripts (plain Node, run manually) — not app code.
    "scripts/**",
  ]),
]);

export default eslintConfig;
